/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'awardsCount' : IDL.Nat,
  'fullDescription' : IDL.Text,
});

export const idlService = IDL.Service({
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getProjectsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'awardsCount' : IDL.Nat,
    'fullDescription' : IDL.Text,
  });
  
  return IDL.Service({
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getProjectsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Project)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };